# Generated by Django 5.1.4 on 2025-01-11 05:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ocrfa_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='pdffile',
            name='name',
            field=models.CharField(default='Asia/Iran', max_length=100),
            preserve_default=False,
        ),
    ]
